<?php

interface Connection
{
    /**
     * Execute a query and return the result
     * @param array<string, string,int,float,bool,null> $params
     */
    public function query(string $query, array $params = []): array;

    /**
     * Run a statement that modifies the database and return the number of affected rows
     * @param array<string, string,int,float,bool,null> $params
     */
    public function execute(string $query, array $params = []): int;

    /**
     * Get the last ID generated by an INSERT statement
     * Should only be called immediately after INSERTing a row
     */
    public function lastInsertId(): int;
}
