---
# Run unit tests on push
name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2

      - uses: actions/cache@v4
        id: cache
        with:
          path: api/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - run: composer install --dev --working-dir=api
        if: steps.cache.outputs.cache-hit != 'true'

      - run: php api/vendor/bin/phpunit api/tests --bootstrap api/tests/bootstrap.php --coverage-html coverage --coverage-filter api/src
        env:
          XDEBUG_MODE: coverage

      - uses: actions/upload-artifact@v4
        with:
          path: coverage
